### ISSUE TITLE
Link gresit

### ISSUE THREAD

**Issue by SebiAlecu** [SoftulmeuRo/pronat#1]
Pasul 1: Am intrat in "Fisa pacientului cu distrofie musculara progresiva tip Duchenne/Becker"
![1](https://cloud.githubusercontent.com/assets/12894907/9990300/d380a6aa-6068-11e5-8f63-f07b463c62ea.png)

Pasul 2: Din drop-down-ul "Rapoarte" am selectat "Lista de pacienti"
![2](https://cloud.githubusercontent.com/assets/12894907/9990323/0d94f51c-6069-11e5-85fd-24b69fc279bf.png)
Pasul 3: Am vrut sa deschid fisa detaliata a pacientului "Ioana Popescu" folosind link-ul:
![3](https://cloud.githubusercontent.com/assets/12894907/9990389/829e7d7e-6069-11e5-8868-7f0262f5be21.png)

Pasul 4: Eroare de link:
![4](https://cloud.githubusercontent.com/assets/12894907/9990427/cb39d4de-6069-11e5-89ec-6da25a08c6e1.png)

**Comment by t1b1c** [comment]
@crystyn90 ce parere ai?

**Comment by crystyn90** [comment]
am modificat si acum merge. 

Sebi, poti sa testezi si tu.

**Comment by SebiAlecu** [comment]
Problema rezolvata
